#!/usr/bin/env bash
set -euo pipefail
ROOT=/home/rspip/cqc/pro/study/orientbench
OUT="$ROOT/audit_bundles/predelete_reproducible_20260818"
mkdir -p "$OUT"
{
  printf 'group\tpath\tbytes\tsha256\tregeneration_reference\n'
  for path in \
    outputs/bench_core/cache \
    outputs/bench_core/gt_index \
    work_dirs \
    outputs/training/a4_host/best_dota_mAP_epoch_70.pth \
    outputs/training/rhino/best_dota_mAP_epoch_35.pth; do
    if [ -d "$ROOT/$path" ]; then
      bytes=$(du -sb "$ROOT/$path" | cut -f1)
      digest=$(find "$ROOT/$path" -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | cut -d' ' -f1)
      ref='repository scripts/configs; cache and work-dir products are regenerated by their originating commands'
      group='A_cache_workdir'
    else
      bytes=$(stat -c %s "$ROOT/$path")
      digest=$(sha256sum "$ROOT/$path" | cut -d' ' -f1)
      group='B_training_checkpoint'
      ref="$(dirname "$path")/manifest.json: launcher_command"
    fi
    printf '%s\t%s\t%s\t%s\t%s\n' "$group" "$path" "$bytes" "$digest" "$ref"
  done
} > "$OUT/predelete_manifest.tsv"
